export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_CLEAR = "SEARCH_CLEAR";

export const ALBUM_LOADING = "ALBUM_LOADING";
export const ALBUM_ERROR = "ALBUM_ERROR";
export const ALBUM_SUCCESS = "ALBUM_SUCCESS";
export const ALBUM_CLEAR = "ALBUM_CLEAR";

export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_RESET = "TOKEN_RESET";

export const PLAYER_ADD_TRACK = "PLAYER_ADD_TRACK";
export const PLAYER_PLAY = "PLAYER_PLAY";
export const PLAYER_STOP = "PLAYER_STOP";
export const PLAYER_WAITING_ALBUM = "PLAYER_WAITING_ALBUM";
