export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_CLEAR = "SEARCH_CLEAR";

export const ALBUM_LOADING = "ALBUM_LOADING";
export const ALBUM_ERROR = "ALBUM_ERROR";
export const ALBUM_SUCCESS = "ALBUM_SUCCESS";
export const ALBUM_CLEAR = "ALBUM_CLEAR";

